
general {
    gaps_in = 5
    gaps_out =  10, 10, 10, 10
    border_size = 2
    col.active_border = $primary $outline 45deg
    col.inactive_border = $outline_var
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}
decoration {
    rounding = 0
    rounding_power = 2
    active_opacity = 1.0
    inactive_opacity = 1.0
    shadow {
        enabled = true
        range = 4
        render_power = 10
        color = rgba(1a1a1aee)
                sharp = false
        ignore_window = true
    }
    blur {
        enabled = false
    }
}

dwindle {
    pseudotile = true    
    preserve_split = true 
}

master {
    new_status = master
}

misc {
    vfr = true
    animate_manual_resizes = false
    animate_mouse_windowdragging = false
}




