

$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun
$bar = ~/.config/waybar/left-round/launch.sh
$theme-set = ~/.config/themes/theme-switcher.sh
$wall-set = ~/.config/themes/wall-cycle.sh
$session = ~/.config/scripts/session.sh
$screenshot = ~/.config/scripts/screenshot.sh
