# ==============================================
# Catppuccin - Hyprland Colors
# ==============================================

$bg          = rgb(1e1e2e)
$fg          = rgb(cdd6f4)
$primary     = rgb(cba6f7)
$on_primary  = rgb(1e1e2e)
$secondary   = rgb(a6e3a1)
$on_sec      = rgb(1e1e2e)
$tertiary    = rgb(fab387)
$surface     = rgb(181825)
$on_surface  = rgb(cdd6f4)
$surf_var    = rgb(313244)
$on_surf_var = rgb(bac2de)
$surf_con    = rgb(45475a)
$surf_hi     = rgb(585b70)
$surf_lo     = rgb(181825)
$error       = rgb(f38ba8)
$outline     = rgb(6c7086)
$outline_var = rgb(45475a)
$inverse_pri = rgb(7287fd)
$magenta     = rgb(f5c2e7)
$cyan        = rgb(89dceb)
$blue        = rgb(89b4fa)
