# ==============================================
# Dracula - Hyprland Colors
# ==============================================

$bg          = rgb(282a36)
$fg          = rgb(f8f8f2)
$primary     = rgb(bd93f9)
$on_primary  = rgb(282a36)
$secondary   = rgb(50fa7b)
$on_sec      = rgb(282a36)
$tertiary    = rgb(ffb86c)
$surface     = rgb(21222c)
$on_surface  = rgb(f8f8f2)
$surf_var    = rgb(44475a)
$on_surf_var = rgb(6272a4)
$surf_con    = rgb(44475a)
$surf_hi     = rgb(6272a4)
$surf_lo     = rgb(191a21)
$error       = rgb(ff5555)
$outline     = rgb(6272a4)
$outline_var = rgb(44475a)
$inverse_pri = rgb(7c6fcd)
$magenta     = rgb(ff79c6)
$cyan        = rgb(8be9fd)
$blue        = rgb(6272a4)
