# ==============================================
# Everforest - Hyprland Colors
# ==============================================

$bg          = rgb(2d3436)
$fg          = rgb(d3c6aa)
$primary     = rgb(a7c080)
$on_primary  = rgb(2d3436)
$secondary   = rgb(83c092)
$on_sec      = rgb(2d3436)
$tertiary    = rgb(dbbc7f)
$surface     = rgb(343f44)
$on_surface  = rgb(d3c6aa)
$surf_var    = rgb(3d4f56)
$on_surf_var = rgb(9da9a0)
$surf_con    = rgb(475258)
$surf_hi     = rgb(56635f)
$surf_lo     = rgb(272e33)
$error       = rgb(e67e80)
$outline     = rgb(7a8478)
$outline_var = rgb(475258)
$inverse_pri = rgb(527d5f)
$magenta     = rgb(d699b6)
$cyan        = rgb(7fbbb3)
$blue        = rgb(7fbbb3)
