# ==============================================
# Gruvbox - Hyprland Colors
# ==============================================

$bg          = rgb(282828)
$fg          = rgb(ebdbb2)
$primary     = rgb(d79921)
$on_primary  = rgb(282828)
$secondary   = rgb(98971a)
$on_sec      = rgb(282828)
$tertiary    = rgb(d65d0e)
$surface     = rgb(32302f)
$on_surface  = rgb(ebdbb2)
$surf_var    = rgb(3c3836)
$on_surf_var = rgb(bdae93)
$surf_con    = rgb(504945)
$surf_hi     = rgb(665c54)
$surf_lo     = rgb(1d2021)
$error       = rgb(cc241d)
$outline     = rgb(928374)
$outline_var = rgb(504945)
$inverse_pri = rgb(b57614)
$magenta     = rgb(b16286)
$cyan        = rgb(689d6a)
$blue        = rgb(458588)
