# ==============================================
# Kanagawa - Hyprland Colors
# ==============================================

$bg          = rgb(1f1f28)
$fg          = rgb(dcd7ba)
$primary     = rgb(7e9cd8)
$on_primary  = rgb(1f1f28)
$secondary   = rgb(98bb6c)
$on_sec      = rgb(1f1f28)
$tertiary    = rgb(e6c384)
$surface     = rgb(16161d)
$on_surface  = rgb(dcd7ba)
$surf_var    = rgb(2a2a37)
$on_surf_var = rgb(c8c093)
$surf_con    = rgb(223249)
$surf_hi     = rgb(363646)
$surf_lo     = rgb(1a1a22)
$error       = rgb(c34043)
$outline     = rgb(727169)
$outline_var = rgb(363646)
$inverse_pri = rgb(658594)
$magenta     = rgb(957fb8)
$cyan        = rgb(7fb4ca)
$blue        = rgb(7e9cd8)
