# ==============================================
# Material - Hyprland Colors
# ==============================================

$bg          = rgb(212121)
$fg          = rgb(eeffff)
$primary     = rgb(82aaff)
$on_primary  = rgb(212121)
$secondary   = rgb(c3e88d)
$on_sec      = rgb(212121)
$tertiary    = rgb(ffcb6b)
$surface     = rgb(1a1a1a)
$on_surface  = rgb(eeffff)
$surf_var    = rgb(2d2d2d)
$on_surf_var = rgb(b0bec5)
$surf_con    = rgb(292929)
$surf_hi     = rgb(353535)
$surf_lo     = rgb(161616)
$error       = rgb(f07178)
$outline     = rgb(546e7a)
$outline_var = rgb(2d2d2d)
$inverse_pri = rgb(3d6eb3)
$magenta     = rgb(c792ea)
$cyan        = rgb(89ddff)
$blue        = rgb(82aaff)
