# ==============================================
# Monochrome - Hyprland Colors
# ==============================================

$bg          = rgb(0e0e0e)
$fg          = rgb(e8e8e8)
$primary     = rgb(ffffff)
$on_primary  = rgb(0e0e0e)
$secondary   = rgb(b0b0b0)
$on_sec      = rgb(0e0e0e)
$tertiary    = rgb(787878)
$surface     = rgb(141414)
$on_surface  = rgb(e8e8e8)
$surf_var    = rgb(1e1e1e)
$on_surf_var = rgb(a0a0a0)
$surf_con    = rgb(242424)
$surf_hi     = rgb(2e2e2e)
$surf_lo     = rgb(0a0a0a)
$error       = rgb(e05c5c)
$outline     = rgb(606060)
$outline_var = rgb(2e2e2e)
$inverse_pri = rgb(383838)
$magenta     = rgb(c8c8c8)
$cyan        = rgb(d0d0d0)
$blue        = rgb(a0a0a0)
