# ==============================================
# Nightfox - Hyprland Colors
# ==============================================

$bg          = rgb(192330)
$fg          = rgb(cdcecf)
$primary     = rgb(81a1c1)
$on_primary  = rgb(192330)
$secondary   = rgb(a3be8c)
$on_sec      = rgb(192330)
$tertiary    = rgb(ebcb8b)
$surface     = rgb(212e3f)
$on_surface  = rgb(cdcecf)
$surf_var    = rgb(29394f)
$on_surf_var = rgb(abb1bb)
$surf_con    = rgb(313e51)
$surf_hi     = rgb(3e4f65)
$surf_lo     = rgb(141f2b)
$error       = rgb(bf616a)
$outline     = rgb(5e6a75)
$outline_var = rgb(29394f)
$inverse_pri = rgb(5b7ea6)
$magenta     = rgb(b48ead)
$cyan        = rgb(88c0d0)
$blue        = rgb(81a1c1)
