# ==============================================
# Nord - Hyprland Colors
# ==============================================

$bg          = rgb(2e3440)
$fg          = rgb(eceff4)
$primary     = rgb(88c0d0)
$on_primary  = rgb(2e3440)
$secondary   = rgb(a3be8c)
$on_sec      = rgb(2e3440)
$tertiary    = rgb(ebcb8b)
$surface     = rgb(3b4252)
$on_surface  = rgb(eceff4)
$surf_var    = rgb(434c5e)
$on_surf_var = rgb(d8dee9)
$surf_con    = rgb(4c566a)
$surf_hi     = rgb(575e6d)
$surf_lo     = rgb(242933)
$error       = rgb(bf616a)
$outline     = rgb(616e88)
$outline_var = rgb(434c5e)
$inverse_pri = rgb(5e81ac)
$magenta     = rgb(b48ead)
$cyan        = rgb(8fbcbb)
$blue        = rgb(81a1c1)
