# ==============================================
# OneDark - Hyprland Colors
# ==============================================

$bg          = rgb(282c34)
$fg          = rgb(abb2bf)
$primary     = rgb(61afef)
$on_primary  = rgb(282c34)
$secondary   = rgb(98c379)
$on_sec      = rgb(282c34)
$tertiary    = rgb(e5c07b)
$surface     = rgb(21252b)
$on_surface  = rgb(abb2bf)
$surf_var    = rgb(3e4452)
$on_surf_var = rgb(828997)
$surf_con    = rgb(2c313a)
$surf_hi     = rgb(353b45)
$surf_lo     = rgb(1d2026)
$error       = rgb(e06c75)
$outline     = rgb(5c6370)
$outline_var = rgb(3e4452)
$inverse_pri = rgb(4e78a0)
$magenta     = rgb(c678dd)
$cyan        = rgb(56b6c2)
$blue        = rgb(61afef)
