# ==============================================
# SolarizedDark - Hyprland Colors
# ==============================================

$bg          = rgb(002b36)
$fg          = rgb(839496)
$primary     = rgb(268bd2)
$on_primary  = rgb(002b36)
$secondary   = rgb(859900)
$on_sec      = rgb(002b36)
$tertiary    = rgb(b58900)
$surface     = rgb(073642)
$on_surface  = rgb(839496)
$surf_var    = rgb(073642)
$on_surf_var = rgb(657b83)
$surf_con    = rgb(073642)
$surf_hi     = rgb(586e75)
$surf_lo     = rgb(00212b)
$error       = rgb(dc322f)
$outline     = rgb(586e75)
$outline_var = rgb(073642)
$inverse_pri = rgb(1a6f8a)
$magenta     = rgb(d33682)
$cyan        = rgb(2aa198)
$blue        = rgb(268bd2)
