# ==============================================
# SolarizedLight - Hyprland Colors
# ==============================================

$bg          = rgb(fdf6e3)
$fg          = rgb(657b83)
$primary     = rgb(268bd2)
$on_primary  = rgb(fdf6e3)
$secondary   = rgb(859900)
$on_sec      = rgb(fdf6e3)
$tertiary    = rgb(b58900)
$surface     = rgb(eee8d5)
$on_surface  = rgb(657b83)
$surf_var    = rgb(eee8d5)
$on_surf_var = rgb(586e75)
$surf_con    = rgb(e8e2cf)
$surf_hi     = rgb(d6d0bd)
$surf_lo     = rgb(f5efdc)
$error       = rgb(dc322f)
$outline     = rgb(93a1a1)
$outline_var = rgb(eee8d5)
$inverse_pri = rgb(268bd2)
$magenta     = rgb(d33682)
$cyan        = rgb(2aa198)
$blue        = rgb(268bd2)
