# ==============================================
# TokyoNight - Hyprland Colors
# ==============================================

$bg          = rgb(1a1b2e)
$fg          = rgb(c0caf5)
$primary     = rgb(7aa2f7)
$on_primary  = rgb(1a1b2e)
$secondary   = rgb(9ece6a)
$on_sec      = rgb(1a1b2e)
$tertiary    = rgb(e0af68)
$surface     = rgb(1f2035)
$on_surface  = rgb(c0caf5)
$surf_var    = rgb(292e42)
$on_surf_var = rgb(a9b1d6)
$surf_con    = rgb(24283b)
$surf_hi     = rgb(2e3248)
$surf_lo     = rgb(1e2030)
$error       = rgb(f7768e)
$outline     = rgb(565f89)
$outline_var = rgb(414868)
$inverse_pri = rgb(3d59a1)
$magenta     = rgb(bb9af7)
$cyan        = rgb(7dcfff)
$blue        = rgb(7aa2f7)
