# ==============================================
# Dracula - Kitty Terminal Colors
# ==============================================

background              #282a36
foreground              #f8f8f2

cursor                  #bd93f9
cursor_text_color       #282a36

selection_background    #44475a
selection_foreground    #f8f8f2

url_color               #bd93f9

active_border_color     #bd93f9
inactive_border_color   #44475a
bell_border_color       #ff5555

active_tab_foreground   #282a36
active_tab_background   #bd93f9
inactive_tab_foreground #6272a4
inactive_tab_background #44475a
tab_bar_background      #191a21

mark1_foreground        #282a36
mark1_background        #bd93f9
mark2_foreground        #282a36
mark2_background        #50fa7b
mark3_foreground        #282a36
mark3_background        #ffb86c

# Black
color0                  #282a36
color8                  #44475a

# Red
color1                  #ff5555
color9                  #ff5555

# Green
color2                  #50fa7b
color10                 #50fa7b

# Yellow
color3                  #ffb86c
color11                 #ffb86c

# Blue
color4                  #6272a4
color12                 #6272a4

# Magenta
color5                  #ff79c6
color13                 #ff79c6

# Cyan
color6                  #8be9fd
color14                 #8be9fd

# White
color7                  #6272a4
color15                 #f8f8f2
