# ==============================================
# Kanagawa - Kitty Terminal Colors
# ==============================================

background              #1f1f28
foreground              #dcd7ba

cursor                  #7e9cd8
cursor_text_color       #1f1f28

selection_background    #2a2a37
selection_foreground    #dcd7ba

url_color               #7e9cd8

active_border_color     #7e9cd8
inactive_border_color   #363646
bell_border_color       #c34043

active_tab_foreground   #1f1f28
active_tab_background   #7e9cd8
inactive_tab_foreground #c8c093
inactive_tab_background #223249
tab_bar_background      #1a1a22

mark1_foreground        #1f1f28
mark1_background        #7e9cd8
mark2_foreground        #1f1f28
mark2_background        #98bb6c
mark3_foreground        #1f1f28
mark3_background        #e6c384

# Black
color0                  #1f1f28
color8                  #363646

# Red
color1                  #c34043
color9                  #c34043

# Green
color2                  #98bb6c
color10                 #98bb6c

# Yellow
color3                  #e6c384
color11                 #e6c384

# Blue
color4                  #7e9cd8
color12                 #7e9cd8

# Magenta
color5                  #957fb8
color13                 #957fb8

# Cyan
color6                  #7fb4ca
color14                 #7fb4ca

# White
color7                  #c8c093
color15                 #dcd7ba
