# ==============================================
# Material - Kitty Terminal Colors
# ==============================================

background              #212121
foreground              #eeffff

cursor                  #82aaff
cursor_text_color       #212121

selection_background    #2d2d2d
selection_foreground    #eeffff

url_color               #82aaff

active_border_color     #82aaff
inactive_border_color   #2d2d2d
bell_border_color       #f07178

active_tab_foreground   #212121
active_tab_background   #82aaff
inactive_tab_foreground #b0bec5
inactive_tab_background #292929
tab_bar_background      #161616

mark1_foreground        #212121
mark1_background        #82aaff
mark2_foreground        #212121
mark2_background        #c3e88d
mark3_foreground        #212121
mark3_background        #ffcb6b

# Black
color0                  #212121
color8                  #2d2d2d

# Red
color1                  #f07178
color9                  #f07178

# Green
color2                  #c3e88d
color10                 #c3e88d

# Yellow
color3                  #ffcb6b
color11                 #ffcb6b

# Blue
color4                  #82aaff
color12                 #82aaff

# Magenta
color5                  #c792ea
color13                 #c792ea

# Cyan
color6                  #89ddff
color14                 #89ddff

# White
color7                  #b0bec5
color15                 #eeffff
