# ==============================================
# Nightfox - Kitty Terminal Colors
# ==============================================

background              #192330
foreground              #cdcecf

cursor                  #81a1c1
cursor_text_color       #192330

selection_background    #29394f
selection_foreground    #cdcecf

url_color               #81a1c1

active_border_color     #81a1c1
inactive_border_color   #29394f
bell_border_color       #bf616a

active_tab_foreground   #192330
active_tab_background   #81a1c1
inactive_tab_foreground #abb1bb
inactive_tab_background #313e51
tab_bar_background      #141f2b

mark1_foreground        #192330
mark1_background        #81a1c1
mark2_foreground        #192330
mark2_background        #a3be8c
mark3_foreground        #192330
mark3_background        #ebcb8b

# Black
color0                  #192330
color8                  #29394f

# Red
color1                  #bf616a
color9                  #bf616a

# Green
color2                  #a3be8c
color10                 #a3be8c

# Yellow
color3                  #ebcb8b
color11                 #ebcb8b

# Blue
color4                  #81a1c1
color12                 #81a1c1

# Magenta
color5                  #b48ead
color13                 #b48ead

# Cyan
color6                  #88c0d0
color14                 #88c0d0

# White
color7                  #abb1bb
color15                 #cdcecf
