# ==============================================
# OneDark - Kitty Terminal Colors
# ==============================================

background              #282c34
foreground              #abb2bf

cursor                  #61afef
cursor_text_color       #282c34

selection_background    #3e4452
selection_foreground    #abb2bf

url_color               #61afef

active_border_color     #61afef
inactive_border_color   #3e4452
bell_border_color       #e06c75

active_tab_foreground   #282c34
active_tab_background   #61afef
inactive_tab_foreground #828997
inactive_tab_background #2c313a
tab_bar_background      #1d2026

mark1_foreground        #282c34
mark1_background        #61afef
mark2_foreground        #282c34
mark2_background        #98c379
mark3_foreground        #282c34
mark3_background        #e5c07b

# Black
color0                  #282c34
color8                  #3e4452

# Red
color1                  #e06c75
color9                  #e06c75

# Green
color2                  #98c379
color10                 #98c379

# Yellow
color3                  #e5c07b
color11                 #e5c07b

# Blue
color4                  #61afef
color12                 #61afef

# Magenta
color5                  #c678dd
color13                 #c678dd

# Cyan
color6                  #56b6c2
color14                 #56b6c2

# White
color7                  #828997
color15                 #abb2bf
