# ==============================================
# RosePine - Kitty Terminal Colors
# ==============================================

background              #191724
foreground              #e0def4

cursor                  #c4a7e7
cursor_text_color       #191724

selection_background    #26233a
selection_foreground    #e0def4

url_color               #c4a7e7

active_border_color     #c4a7e7
inactive_border_color   #403d52
bell_border_color       #eb6f92

active_tab_foreground   #191724
active_tab_background   #c4a7e7
inactive_tab_foreground #908caa
inactive_tab_background #403d52
tab_bar_background      #111019

mark1_foreground        #191724
mark1_background        #c4a7e7
mark2_foreground        #191724
mark2_background        #9ccfd8
mark3_foreground        #191724
mark3_background        #f6c177

# Black
color0                  #191724
color8                  #403d52

# Red
color1                  #eb6f92
color9                  #eb6f92

# Green
color2                  #9ccfd8
color10                 #9ccfd8

# Yellow
color3                  #f6c177
color11                 #f6c177

# Blue
color4                  #31748f
color12                 #31748f

# Magenta
color5                  #eb6f92
color13                 #eb6f92

# Cyan
color6                  #9ccfd8
color14                 #9ccfd8

# White
color7                  #908caa
color15                 #e0def4
