# ==============================================
# SolarizedDark - Kitty Terminal Colors
# ==============================================

background              #002b36
foreground              #839496

cursor                  #268bd2
cursor_text_color       #002b36

selection_background    #073642
selection_foreground    #839496

url_color               #268bd2

active_border_color     #268bd2
inactive_border_color   #073642
bell_border_color       #dc322f

active_tab_foreground   #002b36
active_tab_background   #268bd2
inactive_tab_foreground #657b83
inactive_tab_background #073642
tab_bar_background      #00212b

mark1_foreground        #002b36
mark1_background        #268bd2
mark2_foreground        #002b36
mark2_background        #859900
mark3_foreground        #002b36
mark3_background        #b58900

# Black
color0                  #002b36
color8                  #073642

# Red
color1                  #dc322f
color9                  #dc322f

# Green
color2                  #859900
color10                 #859900

# Yellow
color3                  #b58900
color11                 #b58900

# Blue
color4                  #268bd2
color12                 #268bd2

# Magenta
color5                  #d33682
color13                 #d33682

# Cyan
color6                  #2aa198
color14                 #2aa198

# White
color7                  #657b83
color15                 #839496
