# ==============================================
# Catppuccin - Sway Colors
# ==============================================

set $bg          #1e1e2e
set $fg          #cdd6f4
set $primary     #cba6f7
set $on_primary  #1e1e2e
set $secondary   #a6e3a1
set $on_sec      #1e1e2e
set $tertiary    #fab387
set $surface     #181825
set $on_surface  #cdd6f4
set $surf_var    #313244
set $on_surf_var #bac2de
set $surf_con    #45475a
set $surf_hi     #585b70
set $surf_lo     #181825
set $error       #f38ba8
set $on_error    #1e1e2e
set $outline     #6c7086
set $outline_var #45475a
set $inverse_sur #cdd6f4
set $inverse_pri #7287fd
set $magenta     #f5c2e7
set $cyan        #89dceb
set $blue        #89b4fa

#                       border        background    text          indicator     child_border
client.focused          $primary     $primary     $on_primary  $secondary   $primary
client.focused_inactive $outline_var $surf_hi     $on_surf_var $outline_var $outline_var
client.unfocused        $outline_var $bg          $outline     $outline_var $outline_var
client.urgent           $error       $error       $on_primary  $error       $error
