# ==============================================
# Dracula - Sway Colors
# ==============================================

set $bg          #282a36
set $fg          #f8f8f2
set $primary     #bd93f9
set $on_primary  #282a36
set $secondary   #50fa7b
set $on_sec      #282a36
set $tertiary    #ffb86c
set $surface     #21222c
set $on_surface  #f8f8f2
set $surf_var    #44475a
set $on_surf_var #6272a4
set $surf_con    #44475a
set $surf_hi     #6272a4
set $surf_lo     #191a21
set $error       #ff5555
set $on_error    #f8f8f2
set $outline     #6272a4
set $outline_var #44475a
set $inverse_sur #f8f8f2
set $inverse_pri #7c6fcd
set $magenta     #ff79c6
set $cyan        #8be9fd
set $blue        #6272a4

#                       border        background    text          indicator     child_border
client.focused          $primary     $primary     $on_primary  $secondary   $primary
client.focused_inactive $outline_var $surf_hi     $on_surf_var $outline_var $outline_var
client.unfocused        $outline_var $bg          $outline     $outline_var $outline_var
client.urgent           $error       $error       $on_primary  $error       $error
