# ==============================================
# Everforest - Sway Colors
# ==============================================

set $bg          #2d3436
set $fg          #d3c6aa
set $primary     #a7c080
set $on_primary  #2d3436
set $secondary   #83c092
set $on_sec      #2d3436
set $tertiary    #dbbc7f
set $surface     #343f44
set $on_surface  #d3c6aa
set $surf_var    #3d4f56
set $on_surf_var #9da9a0
set $surf_con    #475258
set $surf_hi     #56635f
set $surf_lo     #272e33
set $error       #e67e80
set $on_error    #2d3436
set $outline     #7a8478
set $outline_var #475258
set $inverse_sur #d3c6aa
set $inverse_pri #527d5f
set $magenta     #d699b6
set $cyan        #7fbbb3
set $blue        #7fbbb3

#                       border        background    text          indicator     child_border
client.focused          $primary     $primary     $on_primary  $secondary   $primary
client.focused_inactive $outline_var $surf_hi     $on_surf_var $outline_var $outline_var
client.unfocused        $outline_var $bg          $outline     $outline_var $outline_var
client.urgent           $error       $error       $on_primary  $error       $error
