# ==============================================
# Gruvbox - Sway Colors
# ==============================================

set $bg          #282828
set $fg          #ebdbb2
set $primary     #d79921
set $on_primary  #282828
set $secondary   #98971a
set $on_sec      #282828
set $tertiary    #d65d0e
set $surface     #32302f
set $on_surface  #ebdbb2
set $surf_var    #3c3836
set $on_surf_var #bdae93
set $surf_con    #504945
set $surf_hi     #665c54
set $surf_lo     #1d2021
set $error       #cc241d
set $on_error    #fbf1c7
set $outline     #928374
set $outline_var #504945
set $inverse_sur #ebdbb2
set $inverse_pri #b57614
set $magenta     #b16286
set $cyan        #689d6a
set $blue        #458588

#                       border        background    text          indicator     child_border
client.focused          $primary     $primary     $on_primary  $secondary   $primary
client.focused_inactive $outline_var $surf_hi     $on_surf_var $outline_var $outline_var
client.unfocused        $outline_var $bg          $outline     $outline_var $outline_var
client.urgent           $error       $error       $on_primary  $error       $error
