# ==============================================
# Kanagawa - Sway Colors
# ==============================================

set $bg          #1f1f28
set $fg          #dcd7ba
set $primary     #7e9cd8
set $on_primary  #1f1f28
set $secondary   #98bb6c
set $on_sec      #1f1f28
set $tertiary    #e6c384
set $surface     #16161d
set $on_surface  #dcd7ba
set $surf_var    #2a2a37
set $on_surf_var #c8c093
set $surf_con    #223249
set $surf_hi     #363646
set $surf_lo     #1a1a22
set $error       #c34043
set $on_error    #dcd7ba
set $outline     #727169
set $outline_var #363646
set $inverse_sur #dcd7ba
set $inverse_pri #658594
set $magenta     #957fb8
set $cyan        #7fb4ca
set $blue        #7e9cd8

#                       border        background    text          indicator     child_border
client.focused          $primary     $primary     $on_primary  $secondary   $primary
client.focused_inactive $outline_var $surf_hi     $on_surf_var $outline_var $outline_var
client.unfocused        $outline_var $bg          $outline     $outline_var $outline_var
client.urgent           $error       $error       $on_primary  $error       $error
