# ==============================================
# Material - Sway Colors
# ==============================================

set $bg          #212121
set $fg          #eeffff
set $primary     #82aaff
set $on_primary  #212121
set $secondary   #c3e88d
set $on_sec      #212121
set $tertiary    #ffcb6b
set $surface     #1a1a1a
set $on_surface  #eeffff
set $surf_var    #2d2d2d
set $on_surf_var #b0bec5
set $surf_con    #292929
set $surf_hi     #353535
set $surf_lo     #161616
set $error       #f07178
set $on_error    #212121
set $outline     #546e7a
set $outline_var #2d2d2d
set $inverse_sur #eeffff
set $inverse_pri #3d6eb3
set $magenta     #c792ea
set $cyan        #89ddff
set $blue        #82aaff

#                       border        background    text          indicator     child_border
client.focused          $primary     $primary     $on_primary  $secondary   $primary
client.focused_inactive $outline_var $surf_hi     $on_surf_var $outline_var $outline_var
client.unfocused        $outline_var $bg          $outline     $outline_var $outline_var
client.urgent           $error       $error       $on_primary  $error       $error
