# ==============================================
# Monochrome - Sway Colors
# ==============================================

set $bg          #0e0e0e
set $fg          #e8e8e8
set $primary     #ffffff
set $on_primary  #0e0e0e
set $secondary   #b0b0b0
set $on_sec      #0e0e0e
set $tertiary    #787878
set $surface     #141414
set $on_surface  #e8e8e8
set $surf_var    #1e1e1e
set $on_surf_var #a0a0a0
set $surf_con    #242424
set $surf_hi     #2e2e2e
set $surf_lo     #0a0a0a
set $error       #e05c5c
set $on_error    #0e0e0e
set $outline     #606060
set $outline_var #2e2e2e
set $inverse_sur #e8e8e8
set $inverse_pri #383838
set $magenta     #c8c8c8
set $cyan        #d0d0d0
set $blue        #a0a0a0

#                       border        background    text          indicator     child_border
client.focused          $primary     $primary     $on_primary  $secondary   $primary
client.focused_inactive $outline_var $surf_hi     $on_surf_var $outline_var $outline_var
client.unfocused        $outline_var $bg          $outline     $outline_var $outline_var
client.urgent           $error       $error       $on_primary  $error       $error
