# ==============================================
# Nightfox - Sway Colors
# ==============================================

set $bg          #192330
set $fg          #cdcecf
set $primary     #81a1c1
set $on_primary  #192330
set $secondary   #a3be8c
set $on_sec      #192330
set $tertiary    #ebcb8b
set $surface     #212e3f
set $on_surface  #cdcecf
set $surf_var    #29394f
set $on_surf_var #abb1bb
set $surf_con    #313e51
set $surf_hi     #3e4f65
set $surf_lo     #141f2b
set $error       #bf616a
set $on_error    #192330
set $outline     #5e6a75
set $outline_var #29394f
set $inverse_sur #cdcecf
set $inverse_pri #5b7ea6
set $magenta     #b48ead
set $cyan        #88c0d0
set $blue        #81a1c1

#                       border        background    text          indicator     child_border
client.focused          $primary     $primary     $on_primary  $secondary   $primary
client.focused_inactive $outline_var $surf_hi     $on_surf_var $outline_var $outline_var
client.unfocused        $outline_var $bg          $outline     $outline_var $outline_var
client.urgent           $error       $error       $on_primary  $error       $error
