# ==============================================
# Nord - Sway Colors
# ==============================================

set $bg          #2e3440
set $fg          #eceff4
set $primary     #88c0d0
set $on_primary  #2e3440
set $secondary   #a3be8c
set $on_sec      #2e3440
set $tertiary    #ebcb8b
set $surface     #3b4252
set $on_surface  #eceff4
set $surf_var    #434c5e
set $on_surf_var #d8dee9
set $surf_con    #4c566a
set $surf_hi     #575e6d
set $surf_lo     #242933
set $error       #bf616a
set $on_error    #eceff4
set $outline     #616e88
set $outline_var #434c5e
set $inverse_sur #eceff4
set $inverse_pri #5e81ac
set $magenta     #b48ead
set $cyan        #8fbcbb
set $blue        #81a1c1

#                       border        background    text          indicator     child_border
client.focused          $primary     $primary     $on_primary  $secondary   $primary
client.focused_inactive $outline_var $surf_hi     $on_surf_var $outline_var $outline_var
client.unfocused        $outline_var $bg          $outline     $outline_var $outline_var
client.urgent           $error       $error       $on_primary  $error       $error
