# ==============================================
# OneDark - Sway Colors
# ==============================================

set $bg          #282c34
set $fg          #abb2bf
set $primary     #61afef
set $on_primary  #282c34
set $secondary   #98c379
set $on_sec      #282c34
set $tertiary    #e5c07b
set $surface     #21252b
set $on_surface  #abb2bf
set $surf_var    #3e4452
set $on_surf_var #828997
set $surf_con    #2c313a
set $surf_hi     #353b45
set $surf_lo     #1d2026
set $error       #e06c75
set $on_error    #282c34
set $outline     #5c6370
set $outline_var #3e4452
set $inverse_sur #abb2bf
set $inverse_pri #4e78a0
set $magenta     #c678dd
set $cyan        #56b6c2
set $blue        #61afef

#                       border        background    text          indicator     child_border
client.focused          $primary     $primary     $on_primary  $secondary   $primary
client.focused_inactive $outline_var $surf_hi     $on_surf_var $outline_var $outline_var
client.unfocused        $outline_var $bg          $outline     $outline_var $outline_var
client.urgent           $error       $error       $on_primary  $error       $error
