# ==============================================
# RosePine - Sway Colors
# ==============================================

set $bg          #191724
set $fg          #e0def4
set $primary     #c4a7e7
set $on_primary  #191724
set $secondary   #9ccfd8
set $on_sec      #191724
set $tertiary    #f6c177
set $surface     #1f1d2e
set $on_surface  #e0def4
set $surf_var    #26233a
set $on_surf_var #908caa
set $surf_con    #403d52
set $surf_hi     #524f67
set $surf_lo     #111019
set $error       #eb6f92
set $on_error    #e0def4
set $outline     #6e6a86
set $outline_var #403d52
set $inverse_sur #e0def4
set $inverse_pri #7a5af8
set $magenta     #eb6f92
set $cyan        #9ccfd8
set $blue        #31748f

#                       border        background    text          indicator     child_border
client.focused          $primary     $primary     $on_primary  $secondary   $primary
client.focused_inactive $outline_var $surf_hi     $on_surf_var $outline_var $outline_var
client.unfocused        $outline_var $bg          $outline     $outline_var $outline_var
client.urgent           $error       $error       $on_primary  $error       $error
