# ==============================================
# SolarizedDark - Sway Colors
# ==============================================

set $bg          #002b36
set $fg          #839496
set $primary     #268bd2
set $on_primary  #002b36
set $secondary   #859900
set $on_sec      #002b36
set $tertiary    #b58900
set $surface     #073642
set $on_surface  #839496
set $surf_var    #073642
set $on_surf_var #657b83
set $surf_con    #073642
set $surf_hi     #586e75
set $surf_lo     #00212b
set $error       #dc322f
set $on_error    #002b36
set $outline     #586e75
set $outline_var #073642
set $inverse_sur #839496
set $inverse_pri #1a6f8a
set $magenta     #d33682
set $cyan        #2aa198
set $blue        #268bd2

#                       border        background    text          indicator     child_border
client.focused          $primary     $primary     $on_primary  $secondary   $primary
client.focused_inactive $outline_var $surf_hi     $on_surf_var $outline_var $outline_var
client.unfocused        $outline_var $bg          $outline     $outline_var $outline_var
client.urgent           $error       $error       $on_primary  $error       $error
