# ==============================================
# SolarizedLight - Sway Colors
# ==============================================

set $bg          #fdf6e3
set $fg          #657b83
set $primary     #268bd2
set $on_primary  #fdf6e3
set $secondary   #859900
set $on_sec      #fdf6e3
set $tertiary    #b58900
set $surface     #eee8d5
set $on_surface  #657b83
set $surf_var    #eee8d5
set $on_surf_var #586e75
set $surf_con    #e8e2cf
set $surf_hi     #d6d0bd
set $surf_lo     #f5efdc
set $error       #dc322f
set $on_error    #fdf6e3
set $outline     #93a1a1
set $outline_var #eee8d5
set $inverse_sur #657b83
set $inverse_pri #268bd2
set $magenta     #d33682
set $cyan        #2aa198
set $blue        #268bd2

#                       border        background    text          indicator     child_border
client.focused          $primary     $primary     $on_primary  $secondary   $primary
client.focused_inactive $outline_var $surf_hi     $on_surf_var $outline_var $outline_var
client.unfocused        $outline_var $bg          $outline     $outline_var $outline_var
client.urgent           $error       $error       $on_primary  $error       $error
