# ==============================================
# TokyoNight - Sway Colors
# ==============================================

set $bg          #1a1b2e
set $fg          #c0caf5
set $primary     #7aa2f7
set $on_primary  #1a1b2e
set $secondary   #9ece6a
set $on_sec      #1a1b2e
set $tertiary    #e0af68
set $surface     #1f2035
set $on_surface  #c0caf5
set $surf_var    #292e42
set $on_surf_var #a9b1d6
set $surf_con    #24283b
set $surf_hi     #2e3248
set $surf_lo     #1e2030
set $error       #f7768e
set $on_error    #1a1b2e
set $outline     #565f89
set $outline_var #414868
set $inverse_sur #c0caf5
set $inverse_pri #3d59a1
set $magenta     #bb9af7
set $cyan        #7dcfff
set $blue        #7aa2f7

#                       border        background    text          indicator     child_border
client.focused          $primary     $primary     $on_primary  $secondary   $primary
client.focused_inactive $outline_var $surf_hi     $on_surf_var $outline_var $outline_var
client.unfocused        $outline_var $bg          $outline     $outline_var $outline_var
client.urgent           $error       $error       $on_primary  $error       $error
